blank_issues_enabled: true
contact_links:
    -   name: UI-Schema Discord
        url: https://discord.gg/MAjgpwnm36
        about: Ask questions and discuss in our Discord Community
    -   name: CodeMirror GitHub
        url: https://github.com/codemirror
        about: "More about the underlying editor framework."
    -   name: Material-UI GitHub
        url: https://github.com/mui-org/material-ui
        about: "Documentation and more for the design framework."
